# Site settings
title: Alfredo Caldas
email: ajscaldas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alfredo Caldas. Laborat처rio de Pr처tese Dental atendendo a regi찾o da Grande Vit처ria.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ajscaldas.github.com" # the base hostname & protocol for your site
facebookurl: "https://www.facebook.com/alfredo.caldas.9"
twitter_username:
github_username:

# Build settings
markdown: kramdown
