
# Site settings
title: Shiyue Li
email: shiyue.li@yale.edu
description: > # this means to ignore newlines until "baseurl:"
  Some math, music and philosophy writings.
# baseurl: "/shiyue-li.github.io" # the subpath of your site, e.g. /blog/
url: "http://shiyue-li.github.io" # the base hostname & protocol for your site
github_username:  shiyue-li

# Build settings
markdown: kramdown
